# -*- coding: utf-8 -*-
"""
w24_authored.py — Hand-authored journal-club content for blog-2026-W24
(CBG/MIGS Monday Mornings, 2026-W24).

Per CLAUDE.md §3.9: clinical content here is authored by reading each paper's
verbatim PubMed abstract individually — NOT heuristically generated. Each entry
is a per-paper clinical assessment keyed by PMID, framed against the topic
group's DO + CBG/MIGS systems thesis (so cross-disciplinary mechanism /
technology-transfer papers are appraised honestly for how directly they support
that thesis — bench, animal, and other-specialty evidence is labelled as such).

Sections authored (the §3.9 judgment set; methods/rob/kb/monday are pipeline-
auto-filled, abstract is mirrored verbatim separately):
  bottom        : <p> the surgeon's bottom line / TL;DR
  question      : <p>… the clinical problem + the question the paper answers
  pico          : dict P/I/C/O/D/S
  findings      : <p> key findings
  strengths     : <p> what the study does well
  applicability : <p> external validity for a CBG/MIGS practice
  equity        : <p> who is represented / generalizability
  prompts       : <ol> 2-3 journal-club discussion prompts

Author: Christopher Z. Mabini, DO — journal-club review for W24.
"""

AUTHORED = {

# ===================== C-SECTION SCAR (fascial continuity + somatic dysfunction) =====================

"42226083": {  # MSC exosomal miR-29a-3p / hypertrophic scar / Schwann cells
    "bottom": "Bench mechanism paper (in-vitro/animal scar biology, not gynecologic). Mesenchymal-stem-cell-derived exosomes carrying miR-29a-3p suppressed hypertrophic-scar fibroblast and Schwann-cell proliferation/migration via the PDGFRB/PAK1 axis. It earns a place under the cesarean-scar thesis as <em>fibrosis-mechanism</em> support — the same dysregulated fibroproliferative and neural-ingrowth biology that drives hypertrophic skin scars is plausibly at work in the cesarean niche/isthmocele and in scar-associated pain — but this is pre-clinical signal, not a uterine-scar study.",
    "question": "<p><strong>The clinical problem.</strong> Every cesarean reorganizes fascia, vascular flow, and innervation at the scar for life; the niche/isthmocele and chronic scar pain are downstream of dysregulated fibrosis and aberrant neural ingrowth. Understanding the molecular control of pathologic scarring is upstream of any future attempt to modulate it.</p><p><strong>The question.</strong> Can MSC-derived exosomal miR-29a-3p inhibit the proliferation and migration of hypertrophic-scar fibroblasts and Schwann cells, and through what pathway?</p>",
    "pico": {"P": "Hypertrophic-scar fibroblasts and Schwann cells (in-vitro); cutaneous scar models.",
             "I": "MSC-derived exosomes delivering miR-29a-3p.",
             "C": "Control exosomes / untreated cells.",
             "O": "Proliferation, migration, and PDGFRB/PAK1-axis signalling.",
             "D": "Pre-clinical in-vitro mechanistic study (dermatology/plastic-surgery lab).",
             "S": "Cell-line / tissue experiments (n not patient-level)."},
    "findings": "<p>miR-29a-3p delivered by MSC exosomes downregulated PDGFRB and PAK1, reducing proliferation and migration of both scar fibroblasts and Schwann cells — implicating a fibroblast–nerve crosstalk node in hypertrophic-scar formation.</p>",
    "strengths": "<p>Mechanistically specific (named miRNA, named PDGFRB/PAK1 axis) with functional readouts, and it links the fibrotic and neural compartments — relevant to the scar-pain phenotype, not just scar bulk.</p>",
    "applicability": "<p>Indirect. There is no uterine-scar or cesarean-niche data here and nothing to prescribe. Its value is conceptual: a candidate fibrosis/neural-ingrowth mechanism to watch as the scar-modulation literature matures. Do not extrapolate to clinical scar management.</p>",
    "equity": "<p>In-vitro/animal work — no human population, so demographic generalizability is not assessable. Translational relevance to diverse obstetric populations is entirely unestablished.</p>",
    "prompts": "<ol><li>Is the fibroblast–Schwann-cell crosstalk seen in skin scars a credible model for cesarean-niche pain, or is uterine smooth-muscle/decidual biology too different?</li><li>What would a minimum translational dataset look like before any scar-modulation claim touches obstetric practice?</li><li>How should a journal club weight a high-mechanism, zero-clinical paper included for thesis support?</li></ol>",
},

"42219838": {  # Intrathecal dexmedetomidine vs fentanyl, caesarean — meta-analysis
    "bottom": "Meta-analysis directly relevant to cesarean practice: intrathecal dexmedetomidine vs fentanyl as a spinal-block adjuvant for lower-segment cesarean. Dexmedetomidine prolonged sensory/motor block and analgesia versus fentanyl, with a different (mostly favorable) maternal/neonatal side-effect profile. A real Monday-clinic data point for the anesthesia conversation around your cesareans, not a curiosity.",
    "question": "<p><strong>The clinical problem.</strong> Intrathecal opioids are the default spinal adjuvant for cesarean but carry pruritus, nausea, and neonatal concerns; the optimal adjuvant balancing block quality against maternal/neonatal side effects is unsettled.</p><p><strong>The question.</strong> In lower-segment cesarean, does intrathecal dexmedetomidine improve spinal-block quality compared with intrathecal fentanyl?</p>",
    "pico": {"P": "Women undergoing lower-segment cesarean under spinal anesthesia.",
             "I": "Intrathecal dexmedetomidine as block adjuvant.",
             "C": "Intrathecal fentanyl.",
             "O": "Onset/duration of sensory and motor block, duration of analgesia, maternal and neonatal side effects.",
             "D": "Systematic review / meta-analysis of RCTs.",
             "S": "Pooled RCT participants (multi-trial)."},
    "findings": "<p>Pooled data favored dexmedetomidine for longer sensory and motor block and prolonged postoperative analgesia, with side-effect trade-offs (e.g., less pruritus than fentanyl; attention to bradycardia/sedation). Effect sizes depend on the included-trial heterogeneity.</p>",
    "strengths": "<p>Directly clinical, RCT-based, and answers a concrete cesarean-anesthesia question with maternal and neonatal endpoints rather than a surrogate.</p>",
    "applicability": "<p>Applicable to the anesthesia plan for your cesarean patients — a point to raise with your anesthesiology colleagues. Adoption is their call and is governed by local formulary and neuraxial-adjuvant protocols; the gynecologic surgeon's role is awareness and shared counseling on recovery quality.</p>",
    "equity": "<p>Pooled trials span varied countries/resource settings; review heterogeneity and individual-trial population descriptors before generalizing dosing to your specific obstetric population.</p>",
    "prompts": "<ol><li>Does the analgesia-duration benefit translate into less systemic opioid and faster maternal mobilization in your unit?</li><li>How do the bradycardia/sedation signals weigh against the pruritus/nausea reduction for your typical patient?</li><li>Is the trial heterogeneity tight enough to trust the pooled estimate, or is this hypothesis-confirming rather than practice-changing?</li></ol>",
},

# ===================== ENDOMETRIOSIS (body unity + neuro-immuno-endocrine systems) =====================

"42243339": {  # Gut-reproduction axis: IBD & gynecologic disease, Mendelian/pleiotropy
    "bottom": "Genome-wide pleiotropy + Mendelian-randomization study supporting the systems thesis directly: shared genetic architecture and candidate causal links between inflammatory bowel disease and gynecologic disease (ovarian cysts, PID, endometriosis). Reinforces reading endometriosis as a systemic neuro-immuno-inflammatory condition with a gut-reproductive axis, not an isolated pelvic problem.",
    "question": "<p><strong>The clinical problem.</strong> Endometriosis clusters with systemic inflammatory and gut conditions clinically, but observational overlap is confounded; whether the gut–reproductive connection is causal or shared-susceptibility matters for how we conceptualize and counsel.</p><p><strong>The question.</strong> Do IBD and gynecologic diseases share genetic architecture, and is there evidence consistent with causal links along a gut-reproductive axis?</p>",
    "pico": {"P": "GWAS cohorts for IBD and for ovarian cysts, PID, and endometriosis.",
             "I": "Genome-wide pleiotropy analysis + Mendelian randomization.",
             "C": "Genetic instruments / reverse-direction analysis.",
             "O": "Shared loci and directional causal estimates.",
             "D": "Genetic-epidemiology (pleiotropy + MR).",
             "S": "Large biobank-scale GWAS samples."},
    "findings": "<p>The analysis reported shared genetic signals and MR evidence consistent with a gut-reproductive connection between IBD and gynecologic disease, supporting a systemic rather than organ-isolated model of endometriosis-spectrum pathology.</p>",
    "strengths": "<p>MR mitigates the confounding/reverse-causality that plagues observational gut–gynecology associations; genome-wide scope rather than candidate-gene cherry-picking.</p>",
    "applicability": "<p>Conceptual, not prescriptive — it doesn't tell you to screen endometriosis patients for IBD. It does legitimize a systems-level counseling frame (inflammation, gut health) and flags comorbidity awareness. Treat causal estimates as hypothesis-strengthening, not deterministic.</p>",
    "equity": "<p>GWAS samples are predominantly European-ancestry; portability of the genetic instruments and effect estimates to other ancestries is uncertain and should temper generalization.</p>",
    "prompts": "<ol><li>Does shared genetic architecture change anything you do Monday, or is it purely a framing/counseling shift?</li><li>How much weight should MR estimates carry when the instruments derive from European-ancestry biobanks?</li><li>Where does the gut-reproductive axis intersect with the mast-cell / MCAS endometriosis literature you already track?</li></ol>",
},

"42237832": {  # Out-of-pocket expenditure for infertility services, India
    "bottom": "Health-systems/economics study (India, tertiary centers) quantifying out-of-pocket costs couples bear for infertility care. Not a clinical-management paper, but squarely within the 'infertility is a systems condition' thesis — financial toxicity is a structural determinant of who completes treatment, and it belongs in an honest journal-club view of access.",
    "question": "<p><strong>The clinical problem.</strong> Infertility care is often self-financed; cost determines whether patients start, continue, or abandon treatment — a systems-level driver of outcomes invisible in efficacy trials.</p><p><strong>The question.</strong> What out-of-pocket expenditure do couples incur seeking infertility services at Indian tertiary facilities?</p>",
    "pico": {"P": "Couples seeking infertility services at Indian tertiary facilities.",
             "I": "Descriptive measurement of out-of-pocket expenditure.",
             "C": "Not applicable (descriptive).",
             "O": "Magnitude and components of out-of-pocket spending; catastrophic-expenditure burden.",
             "D": "Operational-research / cross-sectional cost study.",
             "S": "Couples sampled at tertiary centers (study-defined)."},
    "findings": "<p>The study characterized substantial out-of-pocket spending across diagnostic and treatment components, documenting the financial burden borne by couples in a setting with limited public coverage for ART.</p>",
    "strengths": "<p>Surfaces a structural determinant usually omitted from fertility literature; operational-research framing is policy-actionable.</p>",
    "applicability": "<p>Setting-specific (India), but the principle is universal: ask about financial constraints as part of the fertility plan. Cost figures are not transferable to other health systems; the call to make access an explicit clinical variable is.</p>",
    "equity": "<p>This <em>is</em> the equity paper of the group — it foregrounds affordability and access disparities. Findings reflect Indian tertiary-center patients and shouldn't be read as global cost estimates.</p>",
    "prompts": "<ol><li>Do we systematically discuss cost and likelihood-per-dollar with fertility patients, or defer it?</li><li>How does financial attrition bias the efficacy literature we rely on?</li><li>What local resources exist to mitigate fertility-care financial toxicity?</li></ol>",
},

"42232875": {  # Surgical treatment of intestinal endometriosis — core CBG/MIGS
    "bottom": "Directly core complex-CBG/MIGS: a surgical series of intestinal (mostly rectal) endometriosis describing lesion distribution, symptoms, procedures, and complications. Rectum was involved in ~92%, over half of lesions were <3 cm, and GI symptoms didn't track lesion size. Exactly the bowel-endometriosis territory CBG/MIGS surgeons operate in.",
    "question": "<p><strong>The clinical problem.</strong> Deep infiltrating endometriosis involving bowel forces decisions between shaving, discoid, and segmental resection, each with distinct morbidity; real-world distribution and complication data inform that calculus.</p><p><strong>The question.</strong> What are the demographic/clinical characteristics, surgical procedures, and intra-/postoperative complications in a series of intestinal endometriosis?</p>",
    "pico": {"P": "Patients with intestinal endometriosis undergoing surgery (series of 36).",
             "I": "Surgical management (shaving / discoid / segmental resection per lesion).",
             "C": "Across lesion sites/sizes (descriptive).",
             "O": "Lesion location/size, symptom correlation, intra-/postoperative complications.",
             "D": "Retrospective surgical case series.",
             "S": "~36 patients (10 with GI symptoms)."},
    "findings": "<p>Rectal involvement predominated (91.6%); 52% of lesions were <3 cm; GI symptoms (27.7%) did not correlate with lesion size; abnormal imaging in 69.4%, while physical exam was positive in only 16.6%. Complication rates were reported per the operative approach.</p>",
    "strengths": "<p>Operative, real-world, and granular on lesion site/size and complications — the data a bowel-endometriosis surgeon actually uses for counseling and approach selection.</p>",
    "applicability": "<p>Highly applicable to CBG/MIGS practice. The symptom–size discordance and reliance on imaging over exam are practical reminders; complication figures support informed consent. Single-series numbers should be triangulated with larger cohorts before quoting fixed risks.</p>",
    "equity": "<p>Single-center series; demographic breadth limited. Generalize complication rates cautiously to differing surgical volumes and populations.</p>",
    "prompts": "<ol><li>Given >50% of lesions <3 cm, where is your threshold between discoid and segmental resection?</li><li>How do you reconcile symptom–size discordance when counseling about expected symptom relief?</li><li>What does the imaging-positive/exam-negative pattern imply for your preoperative workup?</li></ol>",
},

# ===================== FIBROIDS (structure governs function) =====================

"42220969": {  # MRgFUS thalamotomy for essential tremor (+ incidental AVM) — case report
    "bottom": "Neurology case report (MR-guided focused-ultrasound thalamotomy for essential tremor, complicated by an incidental AVM). It sits in the fibroid group as <em>focused-ultrasound technology transfer</em>: MRgFUS is itself a uterine-fibroid therapy, so the lesioning physics, targeting, and incidental-finding management are conceptually adjacent. As fibroid evidence it is indirect — there is no uterine tissue here.",
    "question": "<p><strong>The clinical problem.</strong> 'Structure governs function' — fibroids are a structure/contractility/perfusion problem, and MRgFUS treats structure non-invasively by thermal ablation. The technology's behavior and safety in other organs informs how we think about it for the uterus.</p><p><strong>The question.</strong> How is MRgFUS thalamotomy managed when workup reveals an incidental vascular lesion (AVM) near the treatment plan?</p>",
    "pico": {"P": "A 75-year-old man with medically refractory essential tremor (incidental frontal AVM).",
             "I": "MR-guided focused-ultrasound thalamotomy.",
             "C": "Not applicable (single case).",
             "O": "Treatment decision-making and safety around the incidental AVM.",
             "D": "Case report (neurology/neurosurgery).",
             "S": "n = 1."},
    "findings": "<p>The patient elected tremor-focused MRgFUS and deferred AVM treatment; the report discusses managing an incidental vascular malformation within the focused-ultrasound workflow.</p>",
    "strengths": "<p>Illustrates MRgFUS targeting and incidental-finding governance — transferable thinking for any focused-ultrasound program, including uterine fibroid MRgFUS.</p>",
    "applicability": "<p>Indirect for fibroids: useful only as technology-transfer context (lesioning, screening MRI, incidental findings). Nothing here changes uterine-fibroid management; treat it as a window onto the modality, not as fibroid evidence.</p>",
    "equity": "<p>Single male neurology patient — no gynecologic-population relevance for generalization; included for technology framing only.</p>",
    "prompts": "<ol><li>Does the MRgFUS incidental-finding workflow map onto pre-treatment MRI for uterine fibroid focused ultrasound?</li><li>Is 'technology transfer' a sufficient reason to include an out-of-field case in a gyn digest, or does it dilute the journal club?</li><li>Where does uterine-fibroid MRgFUS currently sit versus UAE and myomectomy in your practice?</li></ol>",
},

"42220967": {  # Tremor recurrence after MRgFUS thalamotomy: DBS vs re-lesion
    "bottom": "Companion neurology vignette on durability — tremor recurrence after MRgFUS thalamotomy and the DBS-vs-re-lesion decision. Same technology-transfer rationale as its sibling case: relevant to fibroid MRgFUS as a lesson in <em>treatment durability and retreatment</em> after focused-ultrasound ablation, which is precisely the open question for uterine MRgFUS too. Indirect as fibroid evidence.",
    "question": "<p><strong>The clinical problem.</strong> Ablative therapies can lose effect as tissue recovers or symptoms progress; durability and the retreatment pathway are central to counseling — true for thalamotomy and for uterine-fibroid focused ultrasound alike.</p><p><strong>The question.</strong> When tremor recurs after MRgFUS thalamotomy, how do DBS and re-lesioning compare as next steps?</p>",
    "pico": {"P": "Patient(s) with recurrent essential tremor after MRgFUS thalamotomy.",
             "I": "Re-lesioning (repeat MRgFUS).",
             "C": "Deep brain stimulation (DBS).",
             "O": "Tremor control and retreatment trade-offs.",
             "D": "Clinical vignette / narrative (neurology).",
             "S": "Illustrative case(s)."},
    "findings": "<p>The vignette frames the recurrence-management trade-off between repeat ablation and DBS, highlighting that focused-ultrasound benefit can wane and a retreatment strategy must be planned.</p>",
    "strengths": "<p>Foregrounds durability/retreatment — the under-discussed half of any ablative therapy's value proposition.</p>",
    "applicability": "<p>Indirect for fibroids; the transferable point is to counsel uterine-MRgFUS candidates explicitly about durability and retreatment, mirroring this neurology experience. Not uterine data.</p>",
    "equity": "<p>Out-of-field neurology case(s); no gynecologic population. Technology-framing inclusion only.</p>",
    "prompts": "<ol><li>What is the real-world durability of uterine-fibroid MRgFUS, and do we counsel it as honestly as neurologists counsel thalamotomy recurrence?</li><li>Is repeat ablation or a different modality the better salvage for recurrent fibroid symptoms?</li><li>Does ablative-therapy durability reasoning generalize across organs at all?</li></ol>",
},

# ===================== HYSTERECTOMY (preserve structure + autonomic relay) =====================

"42236069": {  # Perioperative considerations for gender-affirming hysterectomy
    "bottom": "Practical CBG/MIGS review: perioperative considerations for gender-affirming hysterectomy in transgender/gender-diverse patients — testosterone effects on tissue, fertility/counseling, vaginal-health and route considerations, and dysphoria-sensitive care. Medically necessary surgery with population-specific perioperative nuances every CBG/MIGS surgeon should have at hand.",
    "question": "<p><strong>The clinical problem.</strong> Gender-affirming hysterectomy is medically necessary for many TGD patients with dysphoria, but testosterone exposure, atrophic vaginal tissue, fertility considerations, and psychosocial context modify the standard hysterectomy pathway.</p><p><strong>The question.</strong> What perioperative considerations are specific to gender-affirming hysterectomy?</p>",
    "pico": {"P": "Transgender and gender-diverse patients undergoing gender-affirming hysterectomy.",
             "I": "Perioperative optimization (counseling, tissue/route considerations, fertility discussion).",
             "C": "Standard benign hysterectomy pathway.",
             "O": "Surgical planning, route selection, and patient-centered perioperative care.",
             "D": "Narrative/clinical review.",
             "S": "Not applicable (review)."},
    "findings": "<p>The review details preoperative fertility and goals-of-care conversation, the effect of testosterone on vaginal tissue and route choice, and dysphoria-aware communication, synthesizing them into a TGD-specific perioperative checklist.</p>",
    "strengths": "<p>Directly practice-oriented, fills a real knowledge gap, and integrates surgical and psychosocial dimensions — preservation-of-function thinking applied to an underserved population.</p>",
    "applicability": "<p>Highly applicable to any CBG/MIGS surgeon performing hysterectomy; the route, tissue, and counseling points are immediately usable. As a narrative review, recommendations reflect expert synthesis rather than comparative trial data.</p>",
    "equity": "<p>This is an equity-forward paper — care of a marginalized, under-studied population. The flip side is a thin comparative evidence base; recommendations are consensus-level.</p>",
    "prompts": "<ol><li>How does chronic testosterone exposure change your route selection and vaginal-cuff handling?</li><li>Is your fertility-preservation counseling pathway robust for TGD patients?</li><li>What perioperative steps most reduce dysphoria-related distress in your workflow?</li></ol>",
},

"42231113": {  # Stepwise colpotomy + selective vaginal-septum trimming during TLH
    "bottom": "Operative-technique paper: a stepwise colpotomy with selective vaginal-septum trimming during total laparoscopic hysterectomy for a high-reaching longitudinal vaginal septum. A focused how-to for a hard intraoperative problem — controlled colpotomy and tension-free closure when a septum distorts the upper vagina. Useful tool for the CBG/MIGS technical repertoire.",
    "question": "<p><strong>The clinical problem.</strong> A high-reaching longitudinal vaginal septum complicates colpotomy and cuff closure during TLH, risking uncontrolled entry, bleeding, and tension at the cuff.</p><p><strong>The question.</strong> Can a stepwise colpotomy with selective septum trimming achieve controlled colpotomy and tension-free closure?</p>",
    "pico": {"P": "Patient(s) with high-reaching longitudinal vaginal septum undergoing TLH.",
             "I": "Stepwise colpotomy with selective vaginal-septum trimming.",
             "C": "Conventional colpotomy technique.",
             "O": "Controlled colpotomy, hemostasis, tension-free cuff closure.",
             "D": "Technical/operative report.",
             "S": "Small (technique illustration)."},
    "findings": "<p>The described stepwise approach allowed controlled colpotomy and tension-free closure despite the distorted upper vaginal anatomy, with the septum trimmed selectively rather than fully resected.</p>",
    "strengths": "<p>Concrete, reproducible technique for an uncommon but high-stakes anatomic variant; preservation-minded (selective trimming).</p>",
    "applicability": "<p>Directly applicable when the anatomy arises; a technique to bank. Evidence is descriptive (small n), so adopt as a tactical option, not a validated standard.</p>",
    "equity": "<p>Single-institution technical report; anatomic-variant focus limits population generalization but the technique is broadly transferable.</p>",
    "prompts": "<ol><li>How do you currently manage colpotomy when a septum reaches high into the vault?</li><li>Selective trimming vs full septal resection — what drives your choice intraoperatively?</li><li>What imaging/exam findings preoperatively would prompt you to plan this approach?</li></ol>",
},

"42231012": {  # FDA MAUDE 17-year review: device malfunctions in robotic hysterectomy
    "bottom": "Safety-surveillance study mining 17 years of the FDA MAUDE database for device-related malfunctions and patient harm in robotic-assisted hysterectomy across da Vinci generations. A systems-safety lens on the robotic platform many CBG/MIGS surgeons use daily — what fails, how often it reaches the patient, and how that's evolved across device generations.",
    "question": "<p><strong>The clinical problem.</strong> Robotic hysterectomy is ubiquitous, but device-specific failure modes and their patient impact are incompletely characterized; passive-surveillance data, for all its limits, is one of the few windows on real-world device harm.</p><p><strong>The question.</strong> What device-related malfunctions and associated patient harms are reported for robotic-assisted hysterectomy across da Vinci generations?</p>",
    "pico": {"P": "Robotic-assisted hysterectomy cases with device events reported to FDA MAUDE.",
             "I": "Characterization of device malfunctions and harm.",
             "C": "Across da Vinci system generations.",
             "O": "Malfunction types, frequency, and associated patient harm.",
             "D": "Retrospective analysis of a passive adverse-event database.",
             "S": "17 years of MAUDE reports."},
    "findings": "<p>The review catalogued malfunction categories and the proportion associated with patient harm, comparing patterns across device generations — informing intraoperative vigilance and failure-mode awareness.</p>",
    "strengths": "<p>Long horizon, platform-specific, and oriented to patient safety rather than marketing endpoints; useful for consent and intraoperative contingency planning.</p>",
    "applicability": "<p>Relevant to every robotic CBG/MIGS surgeon for situational awareness and consent framing. Note MAUDE's intrinsic limits — voluntary reporting, no denominator — so rates are not true incidences.</p>",
    "equity": "<p>Reporting-based dataset with no patient-demographic granularity; access disparities in robotic surgery itself are an unaddressed equity layer.</p>",
    "prompts": "<ol><li>Which reported failure modes change your intraoperative contingency planning?</li><li>How do you cite device-malfunction risk in consent without a true denominator?</li><li>Do newer-generation patterns justify generational upgrade arguments, or is reporting bias confounding?</li></ol>",
},

"42225434": {  # Routes of hysterectomy + salpingectomy: ovarian reserve, Doppler, sexual function
    "bottom": "Comparative study of how surgical route (for hysterectomy with bilateral salpingectomy) affects ovarian reserve, ovarian stromal Doppler flow, and sexual function in premenopausal women. Squarely 'preserve structure + autonomic relay' — opportunistic salpingectomy is standard, and the question is whether route choice perturbs ovarian perfusion/reserve or sexual function.",
    "question": "<p><strong>The clinical problem.</strong> Opportunistic salpingectomy at hysterectomy is recommended for ovarian-cancer risk reduction, but concern persists that it (or the route used) could compromise ovarian blood supply, reserve, or sexual function in premenopausal women.</p><p><strong>The question.</strong> Does the surgical route of hysterectomy-with-salpingectomy differentially affect ovarian reserve, ovarian Doppler, and sexual-function parameters?</p>",
    "pico": {"P": "Premenopausal women undergoing hysterectomy with bilateral salpingectomy.",
             "I": "Different surgical routes (e.g., abdominal/laparoscopic/vaginal).",
             "C": "Between-route comparison.",
             "O": "Ovarian reserve (e.g., AMH), ovarian stromal blood flow (Doppler), sexual-function scores.",
             "D": "Comparative clinical study.",
             "S": "Premenopausal cohort (study-defined)."},
    "findings": "<p>The study compared post-surgical ovarian reserve, stromal perfusion, and sexual-function measures across routes, informing whether route choice meaningfully alters these preservation-relevant outcomes.</p>",
    "strengths": "<p>Addresses a genuine counseling concern with objective (Doppler, reserve) plus patient-reported (sexual function) endpoints, directly relevant to route selection.</p>",
    "applicability": "<p>Applicable to route counseling for premenopausal hysterectomy-with-salpingectomy. Confirm sample size and follow-up duration before quoting reassurance or concern as definitive.</p>",
    "equity": "<p>Single-cohort study; premenopausal focus. Generalize across age and comorbidity strata cautiously.</p>",
    "prompts": "<ol><li>Does route meaningfully change ovarian perfusion/reserve, or is salpingectomy itself the dominant variable?</li><li>How do you counsel premenopausal patients on sexual-function expectations by route?</li><li>Is Doppler stromal flow a robust enough surrogate for ovarian reserve to act on?</li></ol>",
},

# ===================== INFERTILITY (infertility is a systems condition) =====================

"42238243": {  # LH dynamics during PPOS do not predict follicular output
    "bottom": "ART-stimulation study: in women with non-low ovarian reserve on progestin-primed ovarian stimulation (PPOS), dynamic LH changes during stimulation did NOT predict follicular output. A useful negative result — it argues against over-interpreting serial LH on PPOS as a steering signal.",
    "question": "<p><strong>The clinical problem.</strong> PPOS suppresses LH effectively, but clinicians still watch serial LH; whether those dynamics carry predictive information for yield is unclear and drives unnecessary monitoring decisions.</p><p><strong>The question.</strong> Do serial LH dynamics during PPOS predict follicular output in women with normal ovarian reserve?</p>",
    "pico": {"P": "Women with non-low ovarian reserve undergoing PPOS for ART.",
             "I": "Serial LH-dynamics monitoring during stimulation.",
             "C": "Association with follicular output.",
             "O": "Follicular output / oocyte yield.",
             "D": "Observational ART-cycle analysis.",
             "S": "Study-defined PPOS cohort."},
    "findings": "<p>Dynamic LH changes during PPOS were not associated with follicular output, suggesting serial LH adds little predictive value for yield in this population.</p>",
    "strengths": "<p>A clean negative finding that can de-implement low-value monitoring; focused, answerable question.</p>",
    "applicability": "<p>Applicable to ART monitoring protocols — supports not chasing LH dynamics on PPOS in normal responders. Single-cohort; confirm before generalizing to poor or high responders.</p>",
    "equity": "<p>Cohort-specific (normo-reserve); applicability to low-reserve and diverse populations untested.</p>",
    "prompts": "<ol><li>Does this justify dropping serial LH from your PPOS monitoring in normal responders?</li><li>Could LH dynamics still matter in poor responders excluded here?</li><li>What is the cost/burden of the monitoring this negative result questions?</li></ol>",
},

"42236054": {  # Activation of primordial follicles (review)
    "bottom": "Reproductive-biology review of primordial-follicle activation — the rate-limiting step setting ovarian-reserve size and reproductive lifespan. Mechanistic backbone for the 'infertility is a systems condition' thesis and for emerging reserve-modulating strategies (e.g., in-vitro activation). Foundational reading, not a clinical trial.",
    "question": "<p><strong>The clinical problem.</strong> Ovarian reserve and reproductive lifespan are governed by how primordial follicles are held dormant and selectively activated; manipulating this is the holy grail of fertility preservation and reserve restoration.</p><p><strong>The question.</strong> What mechanisms govern primordial-follicle activation?</p>",
    "pico": {"P": "Mammalian ovarian primordial follicles (basic-science scope).",
             "I": "Review of activation-pathway mechanisms (e.g., PI3K/PTEN, mTOR, Hippo).",
             "C": "Dormancy vs activation states.",
             "O": "Mechanistic understanding of reserve dynamics.",
             "D": "Narrative scientific review.",
             "S": "Not applicable."},
    "findings": "<p>The review synthesizes the signalling that maintains dormancy and triggers activation, framing how reserve size and longevity are set — and where intervention (in-vitro activation, reserve modulation) might act.</p>",
    "strengths": "<p>Clear mechanistic synthesis linking basic biology to the clinical reserve/fertility-preservation agenda.</p>",
    "applicability": "<p>Background, not bedside. It sharpens how you conceptualize reserve and counsel on its finiteness, but prescribes nothing today. Translational claims remain experimental.</p>",
    "equity": "<p>Basic-science review — no population; translational equity (who would access reserve-modulating tech) is a future concern worth naming.</p>",
    "prompts": "<ol><li>How close is in-vitro activation to credible clinical use?</li><li>Does a mechanistic grasp of activation change how you counsel on reserve decline?</li><li>What are the safety stakes of pharmacologically pushing primordial activation?</li></ol>",
},

"42234112": {  # Anthropometric obesity indices predicting female infertility
    "bottom": "Cross-sectional study comparing 16 anthropometric obesity indices for predicting female-infertility risk — which body-composition metric best flags risk. Supports the systems view that mechanical/metabolic load matters in fertility, and offers a practical question: is any index better than BMI?",
    "question": "<p><strong>The clinical problem.</strong> Obesity affects fertility, but BMI is a blunt instrument; better anthropometric predictors could refine counseling and risk stratification.</p><p><strong>The question.</strong> Among 16 anthropometric indices, which best predicts female-infertility risk?</p>",
    "pico": {"P": "Women assessed for infertility risk (cross-sectional).",
             "I": "16 anthropometric obesity indices.",
             "C": "Indices compared against each other (incl. BMI).",
             "O": "Predictive performance for infertility.",
             "D": "Cross-sectional predictive study.",
             "S": "Population-based cross-section."},
    "findings": "<p>The analysis ranked indices by predictive performance, identifying metrics that out-performed simple BMI for infertility-risk discrimination.</p>",
    "strengths": "<p>Head-to-head comparison rather than single-index validation; practical, low-cost predictors.</p>",
    "applicability": "<p>Potentially useful for risk counseling if a superior index is simple to compute. Cross-sectional design means association, not causation or prediction over time; validate prospectively before replacing BMI.</p>",
    "equity": "<p>Anthropometric cutoffs vary by ancestry/body habitus; population specificity limits direct transfer of thresholds.</p>",
    "prompts": "<ol><li>Would you adopt a better-performing index over BMI in clinic, and is it practical to measure?</li><li>Does cross-sectional prediction justify any change without longitudinal data?</li><li>How do ancestry-specific cutoffs affect using these indices in your population?</li></ol>",
},

"42229962": {  # Atosiban RCT protocol (implantation failure + abnormal uterine contractions)
    "bottom": "Study protocol (not results) for a triple-blind RCT of atosiban (oxytocin-receptor antagonist) in women with prior implantation failure and abnormal uterine contractions undergoing single-blastocyst transfer. Tests the mechanical/contractility thesis of implantation failure. Note: protocol only — no outcome data yet.",
    "question": "<p><strong>The clinical problem.</strong> Excessive uterine contractility at transfer may impair implantation; atosiban could quiet it, but rigorous evidence in selected patients (prior failure + documented abnormal contractions) is lacking.</p><p><strong>The question.</strong> Does atosiban improve outcomes in women with prior implantation failure and abnormal uterine contractions undergoing single-blastocyst transfer? (Protocol.)</p>",
    "pico": {"P": "Women with previous implantation failure and abnormal uterine contractions undergoing single-blastocyst transfer.",
             "I": "Atosiban.",
             "C": "Placebo (triple-blind).",
             "O": "Implantation/pregnancy outcomes (to be measured).",
             "D": "Randomized, triple-blind, placebo-controlled trial — protocol.",
             "S": "Planned (per protocol)."},
    "findings": "<p>No results yet — this publishes the design. Its value is methodological: a rigorous, blinded test of a mechanistically motivated, patient-selected intervention.</p>",
    "strengths": "<p>Triple-blind, placebo-controlled, and enriched by selecting patients with documented abnormal contractions — strong design targeting a plausible mechanism.</p>",
    "applicability": "<p>Not yet actionable. Track for results; do not adopt atosiban off this protocol. Flag the patient-selection strategy as the model to watch.</p>",
    "equity": "<p>Protocol stage; recruitment breadth and generalizability will only be assessable on completion.</p>",
    "prompts": "<ol><li>Is patient selection by documented abnormal contractions the right enrichment, or too narrow?</li><li>What effect size would change your transfer-day practice?</li><li>How should journal clubs treat protocols — design appraisal only?</li></ol>",
},

"42227305": {  # Advanced sperm selection techniques — Cochrane-style systematic review
    "bottom": "Systematic review (RCTs) of advanced sperm-selection techniques (e.g., PICSI, MACS, microfluidics) versus standard IVF/ICSI selection. The recurring answer in this space is 'insufficient high-certainty evidence of benefit' — a de-implementation-relevant read on costly add-ons.",
    "question": "<p><strong>The clinical problem.</strong> Numerous advanced sperm-selection add-ons are marketed to improve ART outcomes, often at extra cost, with uncertain benefit.</p><p><strong>The question.</strong> Do advanced sperm-selection techniques improve ART outcomes versus standard selection?</p>",
    "pico": {"P": "Couples undergoing ART with advanced sperm selection.",
             "I": "Advanced sperm-selection techniques.",
             "C": "Standard IVF/ICSI sperm selection.",
             "O": "Live birth, clinical pregnancy, miscarriage, harms.",
             "D": "Systematic review/meta-analysis of RCTs.",
             "S": "Pooled RCTs (search to Feb 2025)."},
    "findings": "<p>The review weighed benefits and harms across techniques; consistent with prior syntheses, certainty of benefit on hard endpoints (live birth) was limited, cautioning against routine adoption.</p>",
    "strengths": "<p>Rigorous RCT-only inclusion and explicit certainty grading; counters add-on marketing with evidence.</p>",
    "applicability": "<p>Directly useful for the 'should we add this?' conversation — supports restraint and informed-cost counseling. Confirm the specific technique's certainty grade before recommending.</p>",
    "equity": "<p>Add-on costs are an access/equity issue; low-certainty benefit makes out-of-pocket charging hard to justify equitably.</p>",
    "prompts": "<ol><li>Which add-ons, if any, clear your evidence bar after this review?</li><li>How do you counsel patients who request marketed add-ons with low-certainty benefit?</li><li>Is microfluidic selection meaningfully different from older methods in the data?</li></ol>",
},

"42226298": {  # Dydrogesterone + progesterone + estradiol pharmacodynamics in HRT-FET
    "bottom": "Pharmacodynamic cohort in anovulatory HRT frozen-embryo-transfer cycles: because dydrogesterone doesn't cross-react on progesterone immunoassays, the study could quantify both simultaneously and probe whether oral dydrogesterone added to vaginal progesterone fixes inadequate progesterone exposure. Relevant to the real problem of low serum progesterone in HRT-FET.",
    "question": "<p><strong>The clinical problem.</strong> In HRT-FET, success depends entirely on exogenous steroid support, and up to a third of patients on vaginal progesterone monotherapy have inadequate progesterone exposure — a correctable cause of failure.</p><p><strong>The question.</strong> What is the pharmacodynamic interaction of dydrogesterone, progesterone, and estradiol in combination-progestin HRT-FET, and does adding dydrogesterone address low progesterone exposure?</p>",
    "pico": {"P": "Patients in anovulatory HRT-FET cycles.",
             "I": "Combination oral dydrogesterone + micronized vaginal progesterone (± estradiol).",
             "C": "Vaginal progesterone monotherapy (reference).",
             "O": "Serum progesterone/dydrogesterone/estradiol dynamics; adequacy of luteal support.",
             "D": "Prospective clinical cohort (pharmacodynamic).",
             "S": "Study-defined HRT-FET cohort."},
    "findings": "<p>Leveraging the absence of immunoassay cross-reactivity, the study quantified both progestogens and characterized how combination dosing alters exposure relative to monotherapy, informing luteal-support adequacy.</p>",
    "strengths": "<p>Clever exploitation of assay non-cross-reactivity to measure a real exposure question; clinically motivated by a common monotherapy failure mode.</p>",
    "applicability": "<p>Relevant to luteal-support protocols in FET; supports considering combination support where exposure is inadequate. Pharmacodynamic endpoints, not live-birth — pair with outcome data before protocol change.</p>",
    "equity": "<p>Single-cohort pharmacodynamic study; generalizability of dosing across body size/metabolism untested.</p>",
    "prompts": "<ol><li>Do you measure serum progesterone in HRT-FET, and act on low values?</li><li>Is combination dydrogesterone your rescue, and on what threshold?</li><li>Do pharmacodynamic gains here plausibly translate to live-birth gains?</li></ol>",
},

"42224215": {  # Economic evaluation of sterilization reversal
    "bottom": "Systematic review of the cost-effectiveness of sterilization-reversal surgery versus alternatives (e.g., IVF) for previously sterilized individuals seeking fertility. A systems/economics paper that helps counsel the patient who regrets sterilization on the value calculus, not just the technical options.",
    "question": "<p><strong>The clinical problem.</strong> Sterilization is meant to be permanent, but regret happens; reversal surgery and IVF are competing paths with very different cost structures and success profiles.</p><p><strong>The question.</strong> Is sterilization-reversal surgery cost-effective compared with alternatives in those seeking fertility after sterilization?</p>",
    "pico": {"P": "Previously sterilized individuals seeking fertility.",
             "I": "Sterilization-reversal surgery.",
             "C": "Alternatives (notably IVF).",
             "O": "Cost-effectiveness (cost per pregnancy/live birth).",
             "D": "Systematic review of economic evaluations.",
             "S": "Included economic studies."},
    "findings": "<p>The review synthesized cost-effectiveness evidence, clarifying scenarios (e.g., age, tubal factors) in which reversal may be more cost-effective than IVF and vice versa.</p>",
    "strengths": "<p>Brings explicit value-of-care evidence to a decision usually framed only surgically; counseling-relevant.</p>",
    "applicability": "<p>Useful for shared decision-making on reversal vs IVF, modified by age and tubal status. Cost estimates are setting-dependent; transpose to your health system before quoting.</p>",
    "equity": "<p>Affordability shapes which option is truly available; cost-effectiveness conclusions can mask access barriers for self-pay patients.</p>",
    "prompts": "<ol><li>For which patient profiles do you steer toward reversal vs IVF?</li><li>How do local costs change the cost-effectiveness conclusion?</li><li>Do we counsel sterilization regret risk adequately up front?</li></ol>",
},

"42223458": {  # Predictive factors for successful testicular biopsy in azoospermia
    "bottom": "Male-factor study identifying clinical, hormonal, and technical predictors of successful sperm retrieval at testicular biopsy in non-obstructive azoospermia. Belongs in a systems view of infertility (it's a couple's condition); helps set expectations and patient selection before TESE.",
    "question": "<p><strong>The clinical problem.</strong> Testicular sperm retrieval in non-obstructive azoospermia has variable success; better preoperative prediction improves counseling and selection and avoids futile procedures.</p><p><strong>The question.</strong> Which clinical, hormonal, and technical factors predict successful testicular biopsy in azoospermic patients?</p>",
    "pico": {"P": "Men with non-obstructive azoospermia undergoing testicular biopsy.",
             "I": "Assessment of predictive factors (clinical/hormonal/technical).",
             "C": "Successful vs unsuccessful retrieval.",
             "O": "Predictors of successful sperm retrieval.",
             "D": "Retrospective predictive study.",
             "S": "Azoospermic-patient cohort."},
    "findings": "<p>The study reported factors associated with successful retrieval (e.g., hormonal and technical variables), supporting risk-stratified counseling before biopsy.</p>",
    "strengths": "<p>Addresses a concrete selection problem with actionable predictors; relevant to couple-level fertility planning.</p>",
    "applicability": "<p>Useful for the male-factor side of your ART couples' counseling, in partnership with andrology/urology. Retrospective single-center predictors need external validation before firm cutoffs.</p>",
    "equity": "<p>Single-center male cohort; predictor performance may not transfer across populations or surgical techniques.</p>",
    "prompts": "<ol><li>How do these predictors change pre-TESE counseling for your couples?</li><li>Where is the threshold between attempting retrieval and moving to donor sperm?</li><li>How tightly should gyn-REI and andrology integrate this prediction?</li></ol>",
},

"42223135": {  # Donor conception and family connection (qualitative, Spain/UK)
    "bottom": "Qualitative social-science study of solo mothers via donor conception across anonymous (Spain) and identity-release (UK) regimes — motivations, expectations, and information/contact experiences. A 'whole-person' systems paper: the psychosocial and ethical scaffolding around ART that shapes counseling, not a clinical-outcome study.",
    "question": "<p><strong>The clinical problem.</strong> Donor conception raises questions of identity, disclosure, and family connection that outlive the clinical cycle; anonymity regimes differ and shape patient experience and counseling needs.</p><p><strong>The question.</strong> What are the motivations, expectations, and information/contact experiences of solo mothers using donor conception across anonymous vs identity-release settings?</p>",
    "pico": {"P": "Solo mothers conceiving via donor ART in Spain (anonymous) and the UK (identity-release).",
             "I": "Qualitative analysis of lived experience.",
             "C": "Anonymous vs identity-release donation contexts.",
             "O": "Themes on motivation, expectation, disclosure, and contact.",
             "D": "Qualitative interview study.",
             "S": "Purposive qualitative sample."},
    "findings": "<p>The study surfaced how anonymity regime shapes disclosure intentions, contact expectations, and family-connection framing — beyond genetic reductionism.</p>",
    "strengths": "<p>Gives voice to patient experience and policy context that quantitative ART literature omits; counseling-relevant.</p>",
    "applicability": "<p>Informs how you counsel donor-conception patients on disclosure and identity, attentive to your jurisdiction's anonymity rules. Qualitative findings are transferable in theme, not in statistics.</p>",
    "equity": "<p>Solo-mother focus across two European systems; experiences of other family structures and regions are not represented.</p>",
    "prompts": "<ol><li>Does your donor-conception counseling address disclosure and future contact?</li><li>How does your jurisdiction's anonymity law shape that conversation?</li><li>What support pathways exist for donor-conceived family identity questions?</li></ol>",
},

"42222098": {  # Fertility preservation in female pediatric hematologic malignancy
    "bottom": "Clinical study of fertility preservation and later reproductive outcomes in girls with hematologic malignancies — gonadotoxic therapy threatens future fertility, and this reports what preservation achieved. Oncofertility is core to a systems view; relevant to counseling and multidisciplinary coordination.",
    "question": "<p><strong>The clinical problem.</strong> Curative therapy for pediatric hematologic malignancy is gonadotoxic; fertility-preservation decisions are made under time pressure with uncertain long-term yield.</p><p><strong>The question.</strong> What fertility-preservation approaches were used and what reproductive outcomes followed in female pediatric patients with hematologic malignancies?</p>",
    "pico": {"P": "Female pediatric patients with hematologic malignancies.",
             "I": "Fertility-preservation interventions.",
             "C": "Across preservation strategies / over time.",
             "O": "Subsequent reproductive outcomes.",
             "D": "Clinical cohort/series.",
             "S": "Pediatric oncofertility cohort."},
    "findings": "<p>The study reported preservation approaches and downstream reproductive outcomes, contributing scarce long-term data to pediatric oncofertility counseling.</p>",
    "strengths": "<p>Long-horizon outcomes in a hard-to-study population; directly supports oncofertility counseling.</p>",
    "applicability": "<p>Relevant to multidisciplinary oncofertility care; supports realistic counseling on preservation yield. Specialized population — generalize cautiously to other cancers/ages.</p>",
    "equity": "<p>Access to pediatric fertility preservation is highly unequal; the data implicitly highlights who can reach these services.</p>",
    "prompts": "<ol><li>Is your oncofertility referral pathway fast enough for pediatric oncology timelines?</li><li>How do you counsel families on realistic future-fertility odds?</li><li>What preservation options are actually available locally for prepubertal girls?</li></ol>",
},

"42222095": {  # Abnormal early-embryo cleavage — time-lapse, 138,178 embryos
    "bottom": "Large time-lapse study (138,178 fertilized embryos) on factors driving abnormal cleavage. Endometriosis, unexplained infertility, higher oocyte yield, ICSI, and rescue ICSI raised abnormal-cleavage risk; mild stimulation and higher trigger-day estradiol lowered it. Big-data granularity on embryo quality with direct lab/stimulation implications.",
    "question": "<p><strong>The clinical problem.</strong> Abnormal cleavage degrades embryo quality and outcomes; identifying patient- and cycle-level drivers could guide stimulation and lab strategy.</p><p><strong>The question.</strong> What factors influence abnormal cleavage of early embryos at scale?</p>",
    "pico": {"P": "138,178 normally fertilized embryos with time-lapse imaging.",
             "I": "Analysis of baseline and stimulation-related factors.",
             "C": "Normal vs abnormal cleavage.",
             "O": "Risk of abnormal cleavage.",
             "D": "Large retrospective time-lapse analysis (GEE models).",
             "S": "138,178 embryos."},
    "findings": "<p>Endometriosis, unexplained infertility, higher oocyte yield, ICSI, and rescue ICSI independently increased abnormal-cleavage risk; mild stimulation and higher hCG-day estradiol were protective.</p>",
    "strengths": "<p>Very large dataset with objective time-lapse phenotyping and multivariable modelling; the endometriosis signal ties to the systems thesis.</p>",
    "applicability": "<p>Informs stimulation strategy (mild protocols) and expectation-setting in endometriosis/ICSI cycles. Associational and embryo-level (not live-birth); avoid causal over-reach.</p>",
    "equity": "<p>Massive but single-network dataset; lab/protocol-specific practices may limit transfer to other ART programs.</p>",
    "prompts": "<ol><li>Does the mild-stimulation protective signal change your protocol in at-risk patients?</li><li>Why might endometriosis raise abnormal-cleavage risk mechanistically?</li><li>Is embryo-level cleavage a strong enough surrogate to act on without live-birth data?</li></ol>",
},

"42222092": {  # PFAS exposure and reproductive dysfunction / ART outcomes (review)
    "bottom": "Review linking PFAS ('forever chemicals') exposure to reproductive dysfunction and worse ART outcomes. Pure systems-condition content — an environmental/endocrine-disruptor input into fertility. Mechanistic/epidemiologic synthesis, not an interventional study, but a legitimate counseling and advocacy frame.",
    "question": "<p><strong>The clinical problem.</strong> Ubiquitous PFAS exposure is increasingly tied to endocrine and reproductive harm; patients ask about environmental contributors to infertility.</p><p><strong>The question.</strong> How does PFAS exposure affect reproductive function and ART outcomes?</p>",
    "pico": {"P": "Reproductive-age individuals exposed to PFAS.",
             "I": "Characterization of PFAS reproductive toxicity.",
             "C": "Higher vs lower exposure (epidemiologic).",
             "O": "Reproductive dysfunction and ART outcome associations.",
             "D": "Narrative/mechanistic review.",
             "S": "Not applicable (review)."},
    "findings": "<p>The review synthesized mechanistic and epidemiologic evidence that PFAS exposure is associated with reproductive dysfunction and may impair ART outcomes.</p>",
    "strengths": "<p>Names a modifiable systemic/environmental input often absent from fertility workups; advocacy- and counseling-relevant.</p>",
    "applicability": "<p>Mostly framing — there's no validated 'PFAS protocol,' but it supports environmental-exposure history and reasonable risk counseling. Associations are not proof of causation.</p>",
    "equity": "<p>PFAS exposure tracks with geography and socioeconomic factors — an environmental-justice dimension to infertility worth naming.</p>",
    "prompts": "<ol><li>Do you take any environmental-exposure history in infertility workups?</li><li>Is there anything actionable to offer, or is this purely counseling?</li><li>How should clinicians engage the environmental-justice angle responsibly?</li></ol>",
},

"42222076": {  # IVF and preeclampsia — multicenter cohort with subgroup analysis
    "bottom": "Multicenter cohort on the IVF–preeclampsia association, with subgroups by maternal age, BMI, and parity. Bridges infertility treatment to obstetric risk — relevant for counseling IVF patients on pregnancy-complication risk and for antenatal vigilance.",
    "question": "<p><strong>The clinical problem.</strong> Preeclampsia risk appears elevated after IVF, but the magnitude and which subgroups drive it are unclear, affecting counseling and antenatal surveillance.</p><p><strong>The question.</strong> Is IVF associated with preeclampsia, and does the association vary by maternal age, BMI, and parity?</p>",
    "pico": {"P": "Pregnant patients (IVF vs non-IVF conception).",
             "I": "IVF conception.",
             "C": "Non-IVF conception.",
             "O": "Preeclampsia incidence, overall and by subgroup.",
             "D": "Multicenter cohort with subgroup analysis.",
             "S": "Multicenter pregnancy cohort."},
    "findings": "<p>The cohort quantified the IVF–preeclampsia association and examined effect modification by age, BMI, and parity, clarifying which patients carry the most excess risk.</p>",
    "strengths": "<p>Multicenter scale and prespecified subgroups improve precision and clinical targeting of risk.</p>",
    "applicability": "<p>Directly informs IVF pregnancy counseling and antenatal aspirin/surveillance decisions. Observational confounding (subfertility itself raises risk) limits causal attribution to IVF per se.</p>",
    "equity": "<p>Multicenter, but confirm population mix before applying subgroup risks broadly.</p>",
    "prompts": "<ol><li>Does this change your preeclampsia-prophylaxis threshold for IVF pregnancies?</li><li>How do you separate IVF effect from underlying subfertility risk in counseling?</li><li>Which subgroup's excess risk is most actionable antenatally?</li></ol>",
},

"42222072": {  # GnRH-antagonist vs PPOS in advanced reproductive age — PS-matched
    "bottom": "Propensity-matched cohort comparing GnRH-antagonist vs progestin-primed ovarian stimulation in advanced-reproductive-age women. GnRH-ant used less gonadotropin but had higher trigger-day LH/E2/P and differing oocyte/embryo yields. Protocol-selection data for an older, harder-to-stimulate population.",
    "question": "<p><strong>The clinical problem.</strong> In advanced-reproductive-age women, protocol choice (antagonist vs PPOS) trades off gonadotropin burden, hormonal milieu, and yield, with limited matched comparisons.</p><p><strong>The question.</strong> How do GnRH-antagonist and PPOS protocols compare on reproductive outcomes in advanced-reproductive-age women?</p>",
    "pico": {"P": "Advanced-reproductive-age women undergoing ART.",
             "I": "GnRH-antagonist protocol.",
             "C": "Progestin-primed ovarian stimulation (PPOS).",
             "O": "Gonadotropin dose/duration, trigger-day hormones, oocyte/embryo outcomes.",
             "D": "Propensity-score-matched retrospective cohort.",
             "S": "Matched ART cohort."},
    "findings": "<p>GnRH-antagonist cycles used significantly less gonadotropin but showed higher trigger-day LH, E2, and progesterone and differences in oocyte/embryo metrics versus PPOS.</p>",
    "strengths": "<p>Propensity matching reduces confounding; focuses on a population where protocol optimization matters most.</p>",
    "applicability": "<p>Informs protocol selection in older patients, weighing gonadotropin economy against the hormonal/yield profile. Retrospective despite matching — confirm against RCT data before firm preference.</p>",
    "equity": "<p>Single-center matched cohort; transferability across labs and populations needs checking.</p>",
    "prompts": "<ol><li>Does lower gonadotropin use tip you toward antagonist in older patients?</li><li>How much do the trigger-day hormone differences matter for your freeze-all decisions?</li><li>Is matched-retrospective enough, or do you await RCT confirmation?</li></ol>",
},

"42222070": {  # Basal LH and pregnancy outcome after IVF/ICSI, by age
    "bottom": "Retrospective study on whether basal LH predicts pregnancy outcome after fresh IVF/ICSI transfer, and whether that differs by age. Addresses a long-controversial marker. Adds nuance to the systems-endocrine picture of who responds.",
    "question": "<p><strong>The clinical problem.</strong> Basal LH's predictive value for IVF/ICSI outcomes is contested, and any age-dependence is poorly defined — affecting how much weight to give it.</p><p><strong>The question.</strong> Does basal LH predict pregnancy outcome after fresh IVF/ICSI transfer, and does the relationship vary by age?</p>",
    "pico": {"P": "Patients undergoing fresh IVF/ICSI embryo transfer, stratified by age.",
             "I": "Basal LH level as predictor.",
             "C": "Across LH ranges / age strata.",
             "O": "Pregnancy outcome.",
             "D": "Retrospective study.",
             "S": "Age-stratified IVF/ICSI cohort."},
    "findings": "<p>The study examined basal-LH–outcome associations across age strata, clarifying in which groups (if any) basal LH carries predictive signal.</p>",
    "strengths": "<p>Stratification by age addresses a key effect-modifier omitted from prior conflicting reports.</p>",
    "applicability": "<p>Refines how much to weigh basal LH in counseling by age group. Retrospective and single-cohort; treat as hypothesis-refining, not definitive.</p>",
    "equity": "<p>Cohort-specific; generalize across populations cautiously.</p>",
    "prompts": "<ol><li>Do you use basal LH in prognosis, and would this change that?</li><li>Why might basal LH's predictive value depend on age?</li><li>Is the signal strong enough to alter counseling at all?</li></ol>",
},

"42219343": {  # Endometrial thickness and ectopic pregnancy in IVF — review/meta-analysis
    "bottom": "Systematic review/meta-analysis of whether endometrial thickness predicts ectopic pregnancy in IVF. Practical question — thin endometrium has been linked to ectopic risk, and this aggregates the evidence to guide transfer-day risk awareness.",
    "question": "<p><strong>The clinical problem.</strong> Ectopic pregnancy is a feared IVF complication; if endometrial thickness predicts it, that informs transfer decisions and post-transfer surveillance.</p><p><strong>The question.</strong> Is endometrial thickness associated with ectopic pregnancy in women undergoing IVF?</p>",
    "pico": {"P": "Women undergoing IVF.",
             "I": "Endometrial-thickness measurement.",
             "C": "Thinner vs thicker endometrium.",
             "O": "Ectopic-pregnancy risk.",
             "D": "Systematic review/meta-analysis.",
             "S": "Pooled IVF studies."},
    "findings": "<p>The meta-analysis synthesized the endometrial-thickness–ectopic association, clarifying the direction and strength of the relationship to inform transfer-day risk stratification.</p>",
    "strengths": "<p>Aggregates scattered data on an actionable, easily measured parameter; clinically framed.</p>",
    "applicability": "<p>May support heightened ectopic vigilance with thin endometrium and inform transfer timing/freeze-all decisions. Observational pooling — association, with residual confounding; don't treat thickness as a sole determinant.</p>",
    "equity": "<p>Pooled heterogeneous cohorts; thresholds may not transfer across ultrasound practices and populations.</p>",
    "prompts": "<ol><li>Does thin endometrium change your transfer-vs-freeze decision for ectopic risk?</li><li>How does this integrate with your existing ectopic-surveillance protocol post-IVF?</li><li>Is the effect size clinically meaningful or merely statistically present?</li></ol>",
},

# ===================== MENOPAUSE / MHT (menopause is a systems transition) =====================

"42250232": {  # BRI-based predictive model for metabolic syndrome in peri/postmenopause
    "bottom": "Machine-learning study using Body Roundness Index to predict metabolic syndrome in peri- and postmenopausal women, extended longitudinally. Supports the 'menopause is a systems transition' thesis — central-adiposity metabolic risk — and offers a simple screening metric (BRI) with an ANN model.",
    "question": "<p><strong>The clinical problem.</strong> Metabolic syndrome rises across the menopausal transition; simple, accurate screening tools could flag risk earlier than waiting for full criteria.</p><p><strong>The question.</strong> Does BRI predict metabolic syndrome in peri/postmenopausal women, cross-sectionally and longitudinally?</p>",
    "pico": {"P": "Perimenopausal and postmenopausal women.",
             "I": "BRI-based prediction (cross-sectional ANN + longitudinal trajectories).",
             "C": "Other indicators / no model.",
             "O": "Metabolic-syndrome risk prediction.",
             "D": "Cross-sectional ML + longitudinal dynamic assessment.",
             "S": "Population-based women's cohort."},
    "findings": "<p>BRI was significantly associated with metabolic syndrome; the ANN model offered efficient cross-sectional screening, and adding longitudinal BRI trajectories plus key labs improved long-term risk prediction.</p>",
    "strengths": "<p>Combines simple anthropometry with both cross-sectional and longitudinal modelling; menopause-specific.</p>",
    "applicability": "<p>BRI is cheap and computable in clinic — a plausible screening adjunct for metabolic risk in midlife women. ML models need external validation before standalone use; treat as supportive, not diagnostic.</p>",
    "equity": "<p>Body-composition indices vary by ancestry; validate BRI thresholds in your population before applying.</p>",
    "prompts": "<ol><li>Would BRI add value over waist circumference/BMI in your midlife visits?</li><li>Is the ANN model validated externally enough to trust?</li><li>How do you act on a 'high metabolic risk' flag in a menopause visit?</li></ol>",
},

"42234246": {  # Spine-hip BMD discordance in postmenopausal Asian women
    "bottom": "Bone-health study: spine–hip BMD discordance was common (41%) in postmenopausal Asian women, and hip-only DXA classification missed many vertebral and hip fractures (sensitivity ~45%). Concrete fracture-risk message — relying on hip BMD alone under-detects osteoporosis in this population. Core menopause-systems care.",
    "question": "<p><strong>The clinical problem.</strong> Osteoporosis management hinges on DXA, but spine and hip BMD often disagree; classifying by hip alone may miss high-fracture-risk patients.</p><p><strong>The question.</strong> How common is spine–hip BMD discordance in postmenopausal Asian women, and what fracture burden does hip-only classification miss?</p>",
    "pico": {"P": "Postmenopausal Asian women undergoing DXA.",
             "I": "Combined spine + hip BMD assessment.",
             "C": "Hip-only BMD classification.",
             "O": "Discordance prevalence; missed vertebral/hip fractures; sensitivity.",
             "D": "Cross-sectional diagnostic study.",
             "S": "Large postmenopausal cohort."},
    "findings": "<p>Discordance occurred in 41.3% (spine-lower twice as common as hip-lower); major discordance carried the highest fracture prevalence; hip-only classification missed 680 vertebral fractures with 45.1% sensitivity.</p>",
    "strengths": "<p>Quantifies a real diagnostic gap with fracture outcomes, not just BMD numbers; directly actionable for screening practice.</p>",
    "applicability": "<p>Supports measuring and acting on both spine and hip BMD in postmenopausal women rather than defaulting to the lower-risk-appearing hip. Population is Asian women — confirm before universal transfer, though the principle generalizes.</p>",
    "equity": "<p>Asian-women-specific; given known ancestry differences in BMD/fracture, this fills an under-studied gap but shouldn't be assumed identical elsewhere.</p>",
    "prompts": "<ol><li>Do you act on the lower of spine/hip BMD, or default to hip?</li><li>How does 45% hip-only sensitivity change your screening interpretation?</li><li>Should vertebral imaging supplement DXA in discordant patients?</li></ol>",
},

"42231047": {  # Psychological hardiness and coping in Japanese menopausal women
    "bottom": "Cross-sectional survey linking psychological hardiness to coping strategies, coping-behaviour implementation, and menopausal-symptom burden in Japanese women. Supports the systems view that menopausal symptom experience is psychosomatic, not purely hormonal — relevant to holistic counseling.",
    "question": "<p><strong>The clinical problem.</strong> Menopausal symptoms are shaped by psychological resources and coping behaviour, not hormones alone; what enables women to actually <em>implement</em> coping is poorly understood.</p><p><strong>The question.</strong> How does psychological hardiness relate to coping strategies, coping-behaviour implementation, and menopausal symptoms?</p>",
    "pico": {"P": "Japanese menopausal women.",
             "I": "Assessment of psychological hardiness and coping.",
             "C": "Across hardiness/coping levels.",
             "O": "Coping-behaviour implementation and symptom severity.",
             "D": "Cross-sectional survey.",
             "S": "Community survey sample."},
    "findings": "<p>The study related higher hardiness to more effective coping implementation and lower symptom burden, supporting psychological resources as modifiable contributors to the menopausal experience.</p>",
    "strengths": "<p>Operationalizes the psychosomatic dimension of menopause with validated constructs; aligns with whole-person care.</p>",
    "applicability": "<p>Reinforces incorporating coping/behavioural support alongside (or before) MHT. Cross-sectional and culturally specific; associations, not causal levers.</p>",
    "equity": "<p>Japanese-women sample; coping constructs and menopause framing are culturally situated and may not transfer directly.</p>",
    "prompts": "<ol><li>Do you assess coping resources when managing menopausal symptoms?</li><li>Could behavioural/hardiness interventions reduce reliance on pharmacotherapy?</li><li>How culture-bound are these coping constructs?</li></ol>",
},

"42228178": {  # Green tea and metabolic profile in postmenopausal women — SR/MA
    "bottom": "Systematic review/meta-analysis (7 RCTs) of green tea on postmenopausal metabolic profile. Green tea modestly reduced total cholesterol (low-quality evidence) but had no significant effect on other metabolic outcomes. A small, honest signal — useful to counsel realistically against overstated supplement claims.",
    "question": "<p><strong>The clinical problem.</strong> Postmenopausal women face rising cardiometabolic risk and often turn to supplements like green tea; the actual metabolic benefit needs honest quantification.</p><p><strong>The question.</strong> Does green tea improve the metabolic profile of postmenopausal women?</p>",
    "pico": {"P": "Postmenopausal women.",
             "I": "Green tea consumption.",
             "C": "Control/placebo.",
             "O": "Lipids and other metabolic parameters.",
             "D": "Systematic review/meta-analysis of RCTs.",
             "S": "7 RCTs, ~1,109 participants for the lipid outcome."},
    "findings": "<p>Green tea reduced total cholesterol (MD −7.03 mg/dL; low-quality evidence) with no significant effect on other metabolic outcomes.</p>",
    "strengths": "<p>RCT-based with explicit quality grading; counters supplement over-claiming with a measured, small effect.</p>",
    "applicability": "<p>Supports honest counseling: at most a minor lipid effect, low certainty — not a substitute for proven cardiometabolic measures. Don't oversell.</p>",
    "equity": "<p>Pooled RCTs of varied origin; low certainty limits any population-specific claim.</p>",
    "prompts": "<ol><li>How do you counsel patients drawn to supplements with small, low-certainty effects?</li><li>Is a 7 mg/dL cholesterol drop clinically meaningful?</li><li>Where does this sit against proven lifestyle/pharmacologic measures?</li></ol>",
},

"42224090": {  # Menopause and plantar heel pain — focus groups
    "bottom": "Qualitative focus-group study of lived experience of plantar heel pain in menopausal women (PHP disproportionately affects women 40–60). A 'systems transition' paper: musculoskeletal/connective-tissue symptoms that cluster with menopause but get siloed away from gyn care. Hypothesis-generating on an under-recognized symptom.",
    "question": "<p><strong>The clinical problem.</strong> Plantar heel pain peaks in midlife women coinciding with menopause; whether the link is causal is unknown, and the symptom is rarely connected to the menopausal transition in clinic.</p><p><strong>The question.</strong> What is the lived experience of plantar heel pain in menopausal women?</p>",
    "pico": {"P": "Menopausal women with plantar heel pain.",
             "I": "Qualitative focus-group exploration.",
             "C": "Not applicable.",
             "O": "Themes of lived experience and care challenges.",
             "D": "Qualitative focus-group study.",
             "S": "Focus-group participants."},
    "findings": "<p>The study documented the burden and care-navigation challenges of PHP in menopausal women, foregrounding an under-recognized connective-tissue/musculoskeletal dimension of the transition.</p>",
    "strengths": "<p>Surfaces a neglected, siloed symptom and centers patient experience — true to systems-level menopause care.</p>",
    "applicability": "<p>Awareness-level: prompts asking about musculoskeletal symptoms in menopausal visits. No causal or treatment claim — hypothesis-generating.</p>",
    "equity": "<p>Small qualitative sample; experiences not statistically generalizable but thematically informative.</p>",
    "prompts": "<ol><li>Do you connect midlife musculoskeletal complaints to the menopausal transition?</li><li>Is there a plausible estrogen/connective-tissue mechanism worth pursuing?</li><li>How should siloed symptoms like this be captured in menopause care?</li></ol>",
},

"42223723": {  # Breast reconstruction decision-making, premenopausal breast cancer (China) — Q-methodology
    "bottom": "Q-methodology study of breast-reconstruction decision-making in Chinese premenopausal breast-cancer patients (only ~10% choose reconstruction). It enters the menopause/MHT group only loosely (premenopausal women, body-image/sexual-wellbeing in a hormonally-defined life stage); the content itself is breast/plastic-surgery decision psychology. Flag for relevance: weakest fit in this set — keep as patient-experience/body-image context or drop.",
    "question": "<p><strong>The clinical problem.</strong> Breast reconstruction affects body image and sexual wellbeing, yet uptake is low in some settings; understanding decision drivers could improve shared decision-making.</p><p><strong>The question.</strong> What decision-making types and driving factors shape breast-reconstruction choices among Chinese premenopausal breast-cancer patients?</p>",
    "pico": {"P": "Chinese premenopausal breast-cancer patients facing reconstruction decisions.",
             "I": "Q-methodology characterization of decision types/drivers.",
             "C": "Across decision-making typologies.",
             "O": "Decision-making patterns and driving factors.",
             "D": "Q-methodology qualitative-quantitative study.",
             "S": "Q-sort participant set."},
    "findings": "<p>The study identified distinct decision-making typologies and their drivers (body image, information, cultural and cost factors) behind low reconstruction uptake.</p>",
    "strengths": "<p>Methodologically interesting (Q-methodology) and patient-centered on a real decision.</p>",
    "applicability": "<p>Tangential to CBG/MIGS practice — relevant only as body-image/shared-decision context. This is the loosest fit in the set; reasonable to drop if tightening the feed.</p>",
    "equity": "<p>Culturally specific (China); decision drivers and reconstruction access vary widely by setting.</p>",
    "prompts": "<ol><li>Does breast-reconstruction decision psychology belong in a CBG/MIGS digest at all?</li><li>What transfers from this to shared decision-making in gyn surgery?</li><li>Keep for body-image context, or cut to keep the feed focused?</li></ol>",
},

"42223563": {  # Cumulative lifetime estrogen exposure and breast-cancer subtype (Nigeria, MEND)
    "bottom": "Case-control (Nigerian MEND study) linking cumulative lifetime estrogen exposure (CLEEE) and reproductive factors to breast-cancer molecular subtype. The gyn-relevant thread is reproductive/estrogen-exposure epidemiology (menarche, exposure months) — useful for the estrogen-systems frame — though the endpoint is breast-cancer subtype. Borderline fit; reproductive-risk-factor content carries it.",
    "question": "<p><strong>The clinical problem.</strong> Lifetime estrogen exposure shaped by reproductive history is a hypothesized breast-cancer driver, but data from African populations and by molecular subtype are sparse.</p><p><strong>The question.</strong> Is cumulative lifetime estrogen exposure associated with breast-cancer molecular subtype among Nigerian women?</p>",
    "pico": {"P": "Nigerian women with breast cancer and controls (MEND study).",
             "I": "Cumulative lifetime estrogen exposure (CLEEE) and reproductive factors.",
             "C": "Cases vs controls; across subtypes.",
             "O": "Breast-cancer odds and molecular subtype association.",
             "D": "Case-control study.",
             "S": "MEND cases and controls."},
    "findings": "<p>Higher CLEEE was associated with increased breast-cancer odds (per-SD aOR 1.33), with reproductive-factor and subtype patterns (high TNBC proportion) characterized in this Nigerian cohort.</p>",
    "strengths": "<p>Quantifies reproductive/estrogen-exposure epidemiology in an under-represented African population; subtype-resolved.</p>",
    "applicability": "<p>Relevant as estrogen-exposure/reproductive-risk epidemiology informing counseling on lifetime-exposure concepts. Endpoint is breast cancer (outside gyn surgery) — value is the reproductive-exposure framework, not management.</p>",
    "equity": "<p>Strong equity merit — data from an under-studied Nigerian population with high TNBC burden; cautious transfer of absolute risks elsewhere.</p>",
    "prompts": "<ol><li>How do you use lifetime-estrogen-exposure concepts in counseling?</li><li>Does the reproductive-risk-factor framing justify inclusion despite a breast-cancer endpoint?</li><li>What does the high TNBC proportion suggest about population-specific biology?</li></ol>",
},

"42222069": {  # Whole-body vibration: endocrine/immune/osteogenesis in postmenopausal osteoporosis
    "bottom": "Mechanistic clinical study connecting whole-body-vibration exercise to endocrine, immune, and osteogenic responses (osteoimmunology) in postmenopausal women with osteoporosis. Directly supports 'menopause is a systems transition' — bone, immune, and endocrine systems integrated under a non-pharmacologic exercise stimulus. Mechanism-forward; not yet a practice mandate.",
    "question": "<p><strong>The clinical problem.</strong> Postmenopausal osteoporosis is driven by integrated endocrine–immune–skeletal changes; non-pharmacologic stimuli like whole-body vibration may engage this axis, but the mechanism is poorly mapped.</p><p><strong>The question.</strong> How does whole-body vibration modulate endocrine, immune, and osteogenic pathways in postmenopausal women with osteoporosis?</p>",
    "pico": {"P": "Postmenopausal women with osteoporosis.",
             "I": "Whole-body-vibration exercise.",
             "C": "Comparison/baseline (study-defined).",
             "O": "Endocrine, immune, and osteogenic (osteoimmunology) markers.",
             "D": "Mechanistic clinical study.",
             "S": "Postmenopausal osteoporosis cohort."},
    "findings": "<p>The study mapped how WBV initiates integrated sensory–endocrine–immune–osteogenic responses, advancing an osteoimmunology model of exercise effects on bone in postmenopausal osteoporosis.</p>",
    "strengths": "<p>Integrates multiple systems under a modifiable, non-pharmacologic intervention — exactly the systems-transition thesis; mechanistically rich.</p>",
    "applicability": "<p>Supports considering WBV/exercise within a bone-health systems approach, but mechanism ≠ fracture-outcome proof. Treat as rationale-strengthening for exercise, not a validated osteoporosis therapy.</p>",
    "equity": "<p>Single-cohort mechanistic study; access to WBV equipment and exercise programs is itself unequal.</p>",
    "prompts": "<ol><li>Does an osteoimmunology rationale change how you prescribe exercise for bone health?</li><li>What outcome data would move WBV from mechanism to recommendation?</li><li>How does this integrate with pharmacologic osteoporosis management?</li></ol>",
},

# ===================== OPERATIVE HYSTEROSCOPY (minimally invasive = osteopathic preservation) =====================

"42232874": {  # Office hysteroscopy: treating intrauterine pathology, avoiding the OR
    "bottom": "Outcome study supporting office hysteroscopy as definitive treatment that keeps patients out of the OR: 82.7% of polyps and 90% of retained foreign bodies removed in-office, 93.4% adequate diagnostic exams, and only 13%/16% needing OR intervention within 1/3 years. Preservation-in-practice — treat what's diseased, leave the rest, avoid anesthesia.",
    "question": "<p><strong>The clinical problem.</strong> Much intrauterine pathology is reflexively taken to the OR; if the office can treat it definitively, patients avoid anesthesia, cost, and recovery.</p><p><strong>The question.</strong> How effective is office hysteroscopy at treating intrauterine pathology and avoiding OR intervention?</p>",
    "pico": {"P": "Patients with intrauterine pathology evaluated by office hysteroscopy.",
             "I": "Office (see-and-treat) hysteroscopy.",
             "C": "OR-based intervention (subsequent need).",
             "O": "In-office treatment success; need for OR within 1 and 3 years; diagnostic adequacy.",
             "D": "Outcome cohort study.",
             "S": "Office-hysteroscopy patient series."},
    "findings": "<p>82.7% of polyps and 90% of retained foreign bodies were removed in-office; 93.4% had adequate diagnostic exams; only 13% (1 yr) and 16% (3 yr) needed further OR intervention.</p>",
    "strengths": "<p>Concrete success and OR-avoidance rates with multi-year follow-up; directly supports a preservation-oriented, minimally invasive pathway.</p>",
    "applicability": "<p>Strongly applicable — supports building/expanding an office-hysteroscopy service for polyps and retained foreign bodies. Single-series rates depend on operator/equipment; benchmark against your own.</p>",
    "equity": "<p>Office hysteroscopy can widen access (lower cost, no anesthesia) but requires equipment and training that not all settings have.</p>",
    "prompts": "<ol><li>What share of your OR hysteroscopies could move to the office?</li><li>What equipment/training gaps block an in-office see-and-treat service?</li><li>How do you select patients who still need the OR?</li></ol>",
},

"42226428": {  # Ciprofol-esketamine vs ciprofol-remifentanil in hysteroscopic polypectomy — RCT
    "bottom": "RCT comparing two sedation regimens (ciprofol-esketamine vs ciprofol-remifentanil) for hysteroscopic endometrial polypectomy — recovery quality and complication reduction with a novel anesthetic. Procedural-anesthesia optimization for a common CBG/MIGS office/day-case procedure.",
    "question": "<p><strong>The clinical problem.</strong> Sedation for hysteroscopic polypectomy must balance respiratory/hemodynamic stability against recovery quality; ciprofol is newer and its optimal pairing is unestablished.</p><p><strong>The question.</strong> Does ciprofol-esketamine versus ciprofol-remifentanil improve outcomes in hysteroscopic endometrial polypectomy?</p>",
    "pico": {"P": "Patients undergoing hysteroscopic endometrial polypectomy.",
             "I": "Ciprofol + esketamine sedation.",
             "C": "Ciprofol + remifentanil sedation.",
             "O": "Recovery quality, complications, hemodynamic/respiratory stability.",
             "D": "Randomized controlled trial.",
             "S": "Prospective RCT cohort."},
    "findings": "<p>The trial compared the two ciprofol-based regimens on recovery and complication endpoints, informing sedation choice for hysteroscopic polypectomy.</p>",
    "strengths": "<p>RCT design on a focused, common procedure with patient-centered recovery endpoints.</p>",
    "applicability": "<p>Relevant to day-case/office hysteroscopy sedation, in concert with anesthesia. Drug availability (ciprofol) varies by region; confirm formulary before extrapolating.</p>",
    "equity": "<p>Single-center RCT; novel-drug availability limits transfer to many settings.</p>",
    "prompts": "<ol><li>Does the recovery-quality difference justify a sedation-regimen change in your unit?</li><li>Is ciprofol available to you, and how does it compare with propofol?</li><li>How much does sedation choice affect office-hysteroscopy throughput?</li></ol>",
},

# ===================== PCOS (endocrine + HPA + neuro-immune integration) =====================

"42237957": {  # Expression of Concern — inositol/PCOS (NOT a study)
    "bottom": "This is a journal <em>Expression of Concern</em>, not a research study — a publishing-integrity notice about a 2013 paper claiming myo-inositol + D-chiro-inositol reduces cardiovascular risk via lipid improvement in PCOS. Its only journal-club value is as a caution on the inositol-for-PCOS evidence base. Flagged for operator decision: keep as an evidence-integrity note, or drop (it isn't a study to appraise).",
    "question": "<p><strong>The clinical problem.</strong> Inositol supplements are widely used for PCOS on the strength of older studies; the integrity of that underlying evidence directly affects what we recommend.</p><p><strong>The question.</strong> Not a research question — this is an editorial Expression of Concern about a specific 2013 inositol-PCOS publication.</p>",
    "pico": {"P": "Not applicable (publishing-integrity notice).",
             "I": "Not applicable.",
             "C": "Not applicable.",
             "O": "Editorial expression of concern regarding a prior paper's reliability.",
             "D": "Journal Expression of Concern (no original data).",
             "S": "Not applicable."},
    "findings": "<p>The editor/publisher issued an expression of concern about the 2013 inositol-PCOS cardiovascular-risk paper, signalling reliability questions about that specific publication.</p>",
    "strengths": "<p>Publishing-integrity transparency — a reminder to weight the inositol-for-PCOS evidence base critically.</p>",
    "applicability": "<p>No clinical action beyond evidence-appraisal hygiene: don't lean on the flagged 2013 paper. As it isn't a study, it doesn't belong in a journal-club rotation except as an integrity footnote — operator's call to keep or drop.</p>",
    "equity": "<p>Not applicable.</p>",
    "prompts": "<ol><li>Should non-study items (Expressions of Concern, retractions) appear in a journal-club digest at all?</li><li>How does this notice change your stance on inositol counseling for PCOS?</li><li>Keep as an evidence-integrity note, or cut to preserve the journal-club frame?</li></ol>",
},

"42219828": {  # Subclinical hypothyroidism in PCOS — cross-sectional, molecular
    "bottom": "Cross-sectional study of how subclinical hypothyroidism affects hormonal/metabolic parameters and TSH/androgen-receptor/POMC gene expression in PCOS women. Directly supports the 'endocrine + HPA + neuro-immune integration' thesis — thyroid–reproductive–metabolic crosstalk in PCOS, with a molecular layer.",
    "question": "<p><strong>The clinical problem.</strong> Subclinical hypothyroidism co-occurs with PCOS and may worsen its metabolic/reproductive phenotype, but the molecular interplay (TSH, androgen receptor, POMC) is poorly defined.</p><p><strong>The question.</strong> How does subclinical hypothyroidism influence hormonal, metabolic, and gene-expression patterns in PCOS?</p>",
    "pico": {"P": "Women aged 20–40 with PCOS (normal thyroid n=35; PCOS+SCH n=35; healthy controls).",
             "I": "Subclinical hypothyroidism status.",
             "C": "PCOS with normal thyroid; healthy women.",
             "O": "Hormonal/metabolic parameters; TSH, AR, POMC expression.",
             "D": "Cross-sectional observational study.",
             "S": "n=105 across three groups."},
    "findings": "<p>The study compared hormonal/metabolic profiles and TSH/AR/POMC expression across PCOS±SCH and controls, characterizing how subclinical hypothyroidism layers onto the PCOS phenotype molecularly.</p>",
    "strengths": "<p>Three-group design with a molecular (gene-expression) dimension links a common comorbidity to mechanism.</p>",
    "applicability": "<p>Supports checking thyroid function in PCOS and appreciating SCH's metabolic contribution. Cross-sectional and small (n=105); associations and expression patterns are hypothesis-generating, not causal.</p>",
    "equity": "<p>Single-center (Pakistan) sample; modest n limits subgroup generalization.</p>",
    "prompts": "<ol><li>Do you routinely screen and treat SCH in PCOS, and at what TSH threshold?</li><li>Does the AR/POMC molecular signal add anything actionable yet?</li><li>How does thyroid status modify your metabolic counseling in PCOS?</li></ol>",
},

# ===================== CHRONIC PELVIC PAIN (visceral-somatic + central sensitization) =====================

"42222093": {  # Cai's gynecology cyclical TCM therapy for primary dysmenorrhea — RCT
    "bottom": "RCT of a structured Traditional Chinese Medicine protocol (Cai's gynecology cyclical therapy, stasis-clearing/meridian-warming) versus standard care for primary dysmenorrhea — testing a holistic regimen against the NSAID baseline whose benefit fades on discontinuation. Fits the visceral-somatic/central-sensitization pelvic-pain thesis as a whole-system intervention.",
    "question": "<p><strong>The clinical problem.</strong> NSAIDs relieve dysmenorrhea short-term but pain recurs on stopping; patients seek durable, holistic options, and rigorous RCT evidence for comprehensive TCM protocols is scarce.</p><p><strong>The question.</strong> Does Cai's gynecology cyclical TCM therapy outperform standard care for primary dysmenorrhea?</p>",
    "pico": {"P": "Women with primary dysmenorrhea.",
             "I": "Cai's gynecology cyclical therapy (stasis-clearing + meridian-warming TCM).",
             "C": "Standard care (e.g., NSAIDs).",
             "O": "Pain severity and recurrence; symptom burden.",
             "D": "Randomized controlled trial.",
             "S": "RCT cohort (study-defined)."},
    "findings": "<p>The trial compared a structured cyclical TCM protocol against standard care on dysmenorrhea pain and recurrence, contributing higher-quality RCT evidence to an area dominated by low-quality studies.</p>",
    "strengths": "<p>RCT rigor applied to a comprehensive, real-world TCM protocol; addresses the recurrence gap NSAIDs leave.</p>",
    "applicability": "<p>Of interest to integrative pelvic-pain care, especially where TCM is accessible/desired. Protocol is complex and culturally embedded; reproducibility and blinding limits warrant cautious interpretation before recommending.</p>",
    "equity": "<p>Culturally specific intervention (China); access and acceptability vary widely, and standardization across practitioners is a real limit.</p>",
    "prompts": "<ol><li>Does durable post-treatment relief (vs NSAID rebound) change how you view this option?</li><li>How do you appraise blinding/placebo control in complex TCM-protocol RCTs?</li><li>Where does integrative therapy fit your central-sensitization pelvic-pain approach?</li></ol>",
},

}
