-- =====================================================================
-- 0007_phase9_snapshots.sql — patient AI snapshot + bidirectional sync
-- =====================================================================
-- Phase 9 — patient context sync between website intake and the
-- MountZara Transcription app, plus the AI-generated PatientProgressSummary
-- ("AI snapshot") that the Transcription app produces via
-- PatientIntelligenceService.generateProgressSummary().
--
-- Architecture:
--   • Website is the canonical source of patient demographics + intake.
--   • Transcription app pulls patient context (intake answers, symptom
--     diary, prior encounters, medications, allergies) via
--     GET /api/v1/sync/transcription/patients?since=... and
--     GET /api/v1/sync/transcription/patients/:id/context
--   • Transcription app runs SOAP + coding + AI snapshot generation with
--     that context, then pushes the result back via
--     POST /api/v1/sync/transcription/snapshot
--   • Website renders the snapshot at /admin/cases/:id/snapshot/ alongside
--     website-only data (symptom diary trends, education progress, messages).
--
-- Mirrors the Swift PatientProgressSummary struct field-by-field so the
-- app can serialize directly into the wire format.
--
-- Idempotent. Re-running is safe.
-- =====================================================================

-- ---------------------------------------------------------------------
-- patient_snapshots — one row per generated AI snapshot.
-- Versioned: new snapshots do NOT overwrite — they append, and the
-- latest_snapshot_id pointer on patients flips. Up to 50 versions per
-- patient (matches the app-side SnapshotHistoryStore cap).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patient_snapshots (
    id                       TEXT PRIMARY KEY,
    patient_id               TEXT NOT NULL,
    -- Where the snapshot was generated
    source_app               TEXT NOT NULL,                 -- 'transcription' | 'clinical_ai' | 'website'
    source_app_snapshot_id   TEXT,                          -- the app's local UUID for SnapshotVersion (de-dup)
    generated_at             INTEGER NOT NULL,              -- Date the snapshot reflects (app's generatedDate)
    encounter_count          INTEGER NOT NULL DEFAULT 0,    -- staleness signal
    encounter_ids_json       TEXT,                          -- JSON array of encounter UUIDs included

    -- Top-level fields from PatientProgressSummary
    clinical_overview        TEXT,                          -- 2-3 sentence summary
    chief_complaint          TEXT,                          -- current/most recent CC
    cc_history               TEXT,                          -- history of presenting complaint
    narrative_patient_story  TEXT,                          -- 150-300 word consultant-tone narrative
    dominant_category        TEXT,                          -- 'obstetric' | 'gynecologic' | 'operative'

    -- Stringly typed arrays — stored as JSON for atomicity, parsed at read time
    patient_goals_json       TEXT,                          -- string[]
    surgical_history_json    TEXT,                          -- string[]
    ai_recommendations_json  TEXT,                          -- string[] of ACOG-anchored recs

    -- Versioning metadata
    version_number           INTEGER NOT NULL DEFAULT 1,    -- 1-based, per patient
    change_notes             TEXT,                          -- 'Added encounter 03/02/2026' / 'Regenerated by user'
    is_current               INTEGER NOT NULL DEFAULT 1,    -- exactly one current per patient (enforced at write)

    -- AI provenance
    ai_model                 TEXT,                          -- 'claude-opus-4-6'
    ai_prompt_version        TEXT,

    created_at               INTEGER NOT NULL,
    updated_at               INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_snapshots_patient_current ON patient_snapshots(patient_id, is_current);
CREATE INDEX IF NOT EXISTS idx_snapshots_patient_generated ON patient_snapshots(patient_id, generated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_snapshots_app_source_id ON patient_snapshots(source_app, source_app_snapshot_id) WHERE source_app_snapshot_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- snapshot_problem_list — structured problem rows.
-- Mirrors Swift ClinicalProblem (problem / status / lastVisitPlan).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshot_problem_list (
    id              TEXT PRIMARY KEY,
    snapshot_id     TEXT NOT NULL,
    seq             INTEGER NOT NULL,                     -- display order
    problem         TEXT NOT NULL,
    status          TEXT NOT NULL,                        -- 'Active' | 'Resolving' | 'Resolved' | 'Monitoring'
    last_visit_plan TEXT,
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problems_snapshot ON snapshot_problem_list(snapshot_id, seq);

-- ---------------------------------------------------------------------
-- snapshot_diagnostic_trends — labs / imaging / procedures.
-- Mirrors Swift DiagnosticTrend (category / testName / entries[] / trendSummary).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshot_diagnostic_trends (
    id              TEXT PRIMARY KEY,
    snapshot_id     TEXT NOT NULL,
    seq             INTEGER NOT NULL,
    category        TEXT NOT NULL,                        -- 'Labs' | 'Imaging' | 'Procedures'
    test_name       TEXT NOT NULL,                        -- 'CBC' | 'Pelvic US' | etc.
    trend_summary   TEXT,                                  -- AI summary of direction + significance
    entries_json    TEXT,                                  -- JSON array of { date, value, interpretation }
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dxtrends_snapshot ON snapshot_diagnostic_trends(snapshot_id, seq);

-- ---------------------------------------------------------------------
-- snapshot_imaging_measurements — organ measurements w/ prior comparison.
-- Mirrors Swift ImagingMeasurement.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshot_imaging_measurements (
    id               TEXT PRIMARY KEY,
    snapshot_id      TEXT NOT NULL,
    seq              INTEGER NOT NULL,
    organ_name       TEXT NOT NULL,                       -- 'Uterus' | 'Right Ovary' | 'Fibroid' | 'Cyst'
    dimension        TEXT NOT NULL,                       -- '8.2 x 4.1 x 3.8 cm'
    measurement_date TEXT,                                  -- 'YYYY-MM-DD' (string from app)
    impression       TEXT,                                  -- 'Normal size, no masses'
    prior_dimension  TEXT,                                  -- previous measurement for delta
    created_at       INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_imaging_snapshot ON snapshot_imaging_measurements(snapshot_id, seq);

-- ---------------------------------------------------------------------
-- snapshot_timeline_events — chronological treatment timeline.
-- Mirrors Swift TimelineEvent.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshot_timeline_events (
    id              TEXT PRIMARY KEY,
    snapshot_id     TEXT NOT NULL,
    seq             INTEGER NOT NULL,                     -- chronological order
    event_date      TEXT,                                  -- 'YYYY-MM-DD'
    event_type      TEXT,                                  -- 'visit' | 'procedure' | 'imaging' | 'lab' | 'diagnosis'
    event_title     TEXT NOT NULL,
    event_detail    TEXT,
    icd10_codes_json TEXT,                                 -- JSON string[]
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_timeline_snapshot ON snapshot_timeline_events(snapshot_id, seq);

-- ---------------------------------------------------------------------
-- snapshot_action_items — AI-recommended next actions.
-- Mirrors Swift ActionItemDescription → ActionItem on save.
-- Distinct from the patient_action_items / care-plan table at /admin/cases —
-- these are SNAPSHOT-derived suggestions awaiting clinician triage.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshot_action_items (
    id               TEXT PRIMARY KEY,
    snapshot_id      TEXT NOT NULL,
    seq              INTEGER NOT NULL,
    description      TEXT NOT NULL,
    priority         TEXT,                                  -- 'high' | 'medium' | 'low'
    due_date         TEXT,                                  -- 'YYYY-MM-DD' or NULL
    rationale        TEXT,
    is_accepted      INTEGER NOT NULL DEFAULT 0,            -- clinician promoted into a real action item
    accepted_at      INTEGER,
    created_at       INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_actions_snapshot ON snapshot_action_items(snapshot_id, seq);

-- ---------------------------------------------------------------------
-- patient_sync_state — bookkeeping for app-side pull cursors.
-- Each app (transcription / clinical_ai / etc.) tracks how far it has
-- pulled. Used by GET /api/v1/sync/transcription/patients?since=cursor
-- to deliver delta only.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patient_sync_state (
    id                TEXT PRIMARY KEY,                   -- '<app>:<patient_id>'
    app               TEXT NOT NULL,
    patient_id        TEXT NOT NULL,
    last_pulled_at    INTEGER NOT NULL,                   -- when the app fetched context
    last_pushed_at    INTEGER,                            -- when the app pushed a snapshot back
    last_snapshot_id  TEXT,                               -- the most-recent snapshot the app pushed
    notes             TEXT,
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sync_state_app ON patient_sync_state(app, last_pulled_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_state_patient ON patient_sync_state(patient_id);

-- ---------------------------------------------------------------------
-- patient_dirty_flag — marker that a patient's context has changed and
-- the next pull should re-deliver them. Written by intake submit /
-- profile update / symptom diary changes etc.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patient_dirty_flag (
    patient_id    TEXT PRIMARY KEY,
    dirty_since   INTEGER NOT NULL,
    dirty_reason  TEXT,                                    -- 'intake_submitted' | 'profile_updated' | 'symptom_logged' | ...
    updated_at    INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dirty_since ON patient_dirty_flag(dirty_since DESC);

-- =====================================================================
-- End of 0007_phase9_snapshots.sql
-- =====================================================================
